package GUI;


import Metier.Partie;
import Metier.Serveur;
import Outils.CustomOutputStream;
import java.io.PrintStream;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Martin
 */
public class ServeurJeu extends javax.swing.JFrame {

    Serveur serveur;
    
    /**
     * Creates new form ServeurJeu
     */
    public ServeurJeu() {
        initComponents();
        
        this.setLocationRelativeTo(this.getParent()); 
        
        // Redirection des messages de la console vers l'interface graphique
        PrintStream infoPrintStream = new PrintStream(new CustomOutputStream(infoConsole));
        PrintStream erreurPrintStream = new PrintStream(new CustomOutputStream(erreurConsole));
        System.setOut(infoPrintStream);
        System.setErr(erreurPrintStream);
        
        System.out.println("Serveur de jeu prêt à être démarré.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNomServeur = new javax.swing.JLabel();
        demarrerBouton = new javax.swing.JButton();
        stopperBouton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoConsole = new javax.swing.JTextArea();
        nomServeur = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        erreurConsole = new javax.swing.JTextArea();
        viderConsoleBouton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STOPPÉ - Serveur de jeu \"Salon #1\"");

        labelNomServeur.setText("Nom du serveur : ");

        demarrerBouton.setText("Démarrer");
        demarrerBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demarrerBoutonActionPerformed(evt);
            }
        });

        stopperBouton.setText("Stoppé");
        stopperBouton.setEnabled(false);
        stopperBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopperBoutonActionPerformed(evt);
            }
        });

        infoConsole.setEditable(false);
        infoConsole.setColumns(20);
        infoConsole.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        infoConsole.setForeground(new java.awt.Color(102, 102, 102));
        infoConsole.setRows(5);
        jScrollPane2.setViewportView(infoConsole);

        nomServeur.setToolTipText("Entrez le nom du serveur...");

        erreurConsole.setColumns(20);
        erreurConsole.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        erreurConsole.setForeground(new java.awt.Color(255, 51, 51));
        erreurConsole.setRows(5);
        jScrollPane1.setViewportView(erreurConsole);

        viderConsoleBouton.setText("Vider console");
        viderConsoleBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viderConsoleBoutonActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNomServeur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomServeur, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(demarrerBouton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stopperBouton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viderConsoleBouton))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(demarrerBouton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(nomServeur)))
                    .addComponent(labelNomServeur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viderConsoleBouton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stopperBouton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void demarrerBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demarrerBoutonActionPerformed
        if(!nomServeur.getText().isEmpty()) {
            nomServeur.setEnabled(false);
            
            serveur = new Serveur(nomServeur.getText());
            serveur.start();

            demarrerBouton.setEnabled(false);
            demarrerBouton.setText("Démarré");

            stopperBouton.setText("Stopper");
            stopperBouton.setEnabled(true);
            
            this.setTitle("DÉMARRÉ - Serveur de jeu \"" + nomServeur.getText() + "\"");
        }
        else {
            JOptionPane.showMessageDialog(null, "Veuillez saisir un nom pour le serveur de jeu.");
        }
    }//GEN-LAST:event_demarrerBoutonActionPerformed

    private void stopperBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopperBoutonActionPerformed
        serveur.stopper();
        
        stopperBouton.setEnabled(false);
        stopperBouton.setText("Stoppé");
        
        demarrerBouton.setText("Démarrer");
        demarrerBouton.setEnabled(true);
        
        nomServeur.setEnabled(true);
        
        this.setTitle("STOPPÉ - Serveur de jeu \"" + nomServeur.getText() + "\"");
    }//GEN-LAST:event_stopperBoutonActionPerformed

    private void viderConsoleBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viderConsoleBoutonActionPerformed
        infoConsole.setText("");
        erreurConsole.setText("");
    }//GEN-LAST:event_viderConsoleBoutonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!serveur.test(this.jTextField1.getText()))
        {
            JOptionPane.showMessageDialog(null, "Mauvaise carte");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServeurJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServeurJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServeurJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServeurJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServeurJeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton demarrerBouton;
    private javax.swing.JTextArea erreurConsole;
    private javax.swing.JTextArea infoConsole;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelNomServeur;
    private javax.swing.JTextField nomServeur;
    private javax.swing.JButton stopperBouton;
    private javax.swing.JButton viderConsoleBouton;
    // End of variables declaration//GEN-END:variables
}
